name: Deploy HTML Project to AWS

on:
  push:
    branches:
      - main  # Runs when code is pushed to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug SSH Key (Optional)
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > private_key.pem
          sudo chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "echo '✅ SSH Connection Successful'"
          
      - name: Add GitHub to known_hosts (ensure SSH connection to GitHub)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Deploy to EC2 (Ubuntu)
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > private_key.pem
          sudo chmod 600 private_key.pem

          echo "🔄 Removing old files..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            sudo rm -rf /var/www/spbook.in/*
            exit
          EOF

          echo "🚀 Uploading new files..."
          scp -i private_key.pem -o StrictHostKeyChecking=no -r * ${{ secrets.EC2_HOST }}:/var/www/spbook.in/

          echo "🔄 Restarting Nginx..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'

      - name: Cleanup
        run: rm -f private_key.pem
